# Traceability: [DALC-REQ-DALC-PKG-002]
# Values for subchart alias `agent` (library chart name: declarative-agent-library-chart)
agent:
  systemPrompt: |
    Respond, "Hello :wave:"
  systemPromptFile: ""
  image:
    repository: declarative-agent-library-chart
    tag: local
    pullPolicy: Never
