# Values for subchart alias `declarative-agent` (library chart name: declarative-agent-library-chart)
declarative-agent:
  systemPrompt: |
    Respond, "Hello :wave:"
  image:
    repository: declarative-agent
    tag: local
    pullPolicy: Never
