apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "declarative-agent-library.fullname" . }}-config
  labels:
    {{- include "declarative-agent-library.labels" . | nindent 4 }}
data:
  system-prompt: |
{{ .Values.systemPrompt | nindent 4 }}
  subagents.json: {{ .Values.subagents | toJson | quote }}
  skills.json: {{ .Values.skills | toJson | quote }}
  enabled-mcp-tools.json: {{ .Values.mcp.enabledTools | toJson | quote }}
